### ISSUE TITLE
(start) hangs repl

### ISSUE THREAD

**Issue by royalaid** [luminus-framework/luminus-alpeh#1]
When running luminus with the `+aleph` configuration and calling `(start)` from the repl causes it to hang. My guess is the call to `wait-for-close`.  It would great to spin it off into another thread that can be killed.

**Comment by yogthos** [comment]
Yeah, that definitely looks to be the problem. I'm thinking `wait-for-close` isn't even necessary. Aleph should stick around until the REPL or `lein run` finishes without it. This would need a bit of testing though.

**Comment by royalaid** [comment]
If I get some time this weekend I can fork and see if it works for my use
case and report back.

**Comment by yogthos** [comment]
👍
